### PR TITLE
Update to WASDK 1.3.230502000 (delete workaround for xaml title)

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title ^^.

### CODE REVIEW

**Comment by dotMorten** [comment]
Not sure how this passed the validation build. I figured this was a breaking change, but the validation build said OK.
However when I went to publish this, it did indeed fail:
```
C:\Users\runneradmin\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.7.21379.12\build\Microsoft.DotNet.PackageValidation.targets(22,5): error CP0002: Member 'WinUIEx.WindowEx.Title.set' exists on [Baseline] lib/net6.0-windows10.0.18362/WinUIEx.dll but not on lib/net6.0-windows10.0.18362/WinUIEx.dll [D:\a\WinUIEx\WinUIEx\src\WinUIEx\WinUIEx.csproj]
```

**Comment by andreyrd** [comment]
This makes WinUIEx incompatible with .NET7.0+MAUI
https://github.com/dotnet/maui/issues/14107

**Comment by dotMorten** [comment]
Not following. That issue says the same thing - explicitly reference 1.3 of WinAppSDK. That’s just how nuget and dependencies work

**Comment by andreyrd** [comment]
Oh! Awesome, thank you so much. I had thought I just couldn't upgrade because of the PrecompiledHeader exception. I'll restart VS.

**Comment by dotMorten** [comment]
Yeah it’s an annoying bug. I was told at build that it’s fixed and should be ready in the next patch

**Comment by dotMorten** [comment]
The error message tells me this is a project configuration issue and has nothing to do with WinUIEx

**Comment by Magic73** [comment]
I haven't wrote anything about WinUIEx. the issue is about the need to upgrade Microsoft.WindowsAppSDK to 1.3 or above, due to the error:  https://github.com/dotnet/maui/issues/10102

**Comment by dotMorten** [comment]
@Magic73 but this repo is for WinUIEx

**Comment by Magic73** [comment]
DOH :( you're right. sorry

**Comment by AnithaRaniT** [comment]
Hello, I got the same issue, as per the suggestions i added the below code,

<ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows10.0.17763'"> <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230331000" /> </ItemGroup>

after adding the bove one also not able to publish the app package for the windows platform.

Here is my target platforms:
	<TargetFrameworks>net7.0-ios;net7.0-android33.0</TargetFrameworks> <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.20348.0</TargetFrameworks>


Can some one suggest something to make it work. I don't see any possible sollution in the internet.

**Comment by dotMorten** [comment]
Your windows condition for the package reference doesn't match the target framework you actually compile for (different windows sdk versions)

**Comment by AnithaRaniT** [comment]
@dotMorten thanks for that, I tried the matching sdk as well like below

`<TargetFrameworks>net7.0-ios;net7.0-android33.0</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		`


`  <ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows10.0.19041.0'">   
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230331000" />
  </ItemGroup>`

But no luck.

**Comment by dotMorten** [comment]
ok. An old closed PR in a repo that isn't Maui or Windows App SDK repo probably isn't the right place to be trouble-shooting this though.

**Comment by AnithaRaniT** [comment]
@dotMorten  which repo you are talking about? Is there a way can get the fix for this? Or any suggestions?

**Comment by dotMorten** [comment]
I don't see anything in the little bit of information you provided to indicate you're dealing with an issue in WinUIEx, which is the only thing that belongs here. I don't have enough information either to point you to where to go, but again this isn't the place for this. Perhaps try the Microsoft community forums first and include as much information as possible including a simple sample that reproduces the issue

**Pull request merged**
