### PR TITLE
Improve sample app UI

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
Improved and fixed some issues on the sample app.

### CODE REVIEW

**Comment by dotMorten** [comment]
I'm at Build right now so can't test it but what is this specifically addressing?

**Comment by AndrewKeepCoding** [comment]
Just improved a couple of margin settings and fixed the Settings page title from "Windows Design" to "Settings". Nothing critical.

**Comment by dotMorten** [comment]
Maybe I'm just not clear on what was wrong with them in the first place?
Also not sure I get the rename to settings.

**Comment by AndrewKeepCoding** [comment]
For example, in the **Windows Control** page, the buttons have inconsistent look and spacing. One of them not showing its entire content:
image
This is how it looks after the change:
image

**Comment by AndrewKeepCoding** [comment]
I aslso fixed the **Settings** page title:
image
to:
image

**Comment by AndrewKeepCoding** [comment]
This PR has become old. Closing it.

**Pull request closed without merging**
